main: btor-test.c
	gcc -o test.out btor-test.c /home/makaim/repos/boolector/deps/btor2tools/build/btor2parser.o /usr/local/lib/libboolector.a /home/makaim/repos/boolector/deps/lingeling/liblgl.a -lm -lpthread

clean:
	rm -rf *.out *.o
